### ISSUE TITLE
wider drop down menu

### ISSUE THREAD

**Issue by ShalokShalom** [joeytwiddle/code#1]
Hi there, I already put that issue in the Github Dark issue page, you probably remember: 

![screenshot_20170715_191339](https://user-images.githubusercontent.com/6344099/28241276-bf51cf36-6991-11e7-98a2-cd4d9b851a00.png)

**Comment by joeytwiddle** [comment]
Good idea. Will look at it later.

**Comment by joeytwiddle** [comment]
I have [added 200px](https://github.com/joeytwiddle/code/commit/aa1874a6d01fc16ba1ffedf62ac749194a4fba86) so that column can now reach 400px width. Seems like there's no point allowing any more, as Github truncates the text before giving it to the client.

**Comment by ShalokShalom** [comment]
Thanks a lot ^-^

**Comment by ShalokShalom** [comment]
With this update, drop down menu does not appear anymore.
