### ISSUE TITLE
(Github Notifications Dropdown) Conflicting collapsible blocks feature

### ISSUE THREAD

**Issue by jerone** [joeytwiddle/code#2]
Hi, loving your [ Github Notifications Dropdown](https://github.com/joeytwiddle/code/blob/master/other/gm_scripts/github_notifications_dropdown/github_notifications_dropdown.user.js) userscript for the notifications dropdown.
The [hidden feature for collapsible blocks](https://github.com/joeytwiddle/code/blob/master/other/gm_scripts/github_notifications_dropdown/github_notifications_dropdown.user.js#L309-L317) however not so much. It's actually conflicting with some other scripts I have installed.
I don't want to edit the userscript and lose updates. So I was wondering if you want to remove that feature from this userscript (and maybe make a separate userscript from it)...

------
_<https://openuserjs.org/scripts/joeytwiddle/Github_Notifications_Dropdown/issues/Conflicting_collapsible_blocks_feature>_

**Comment by joeytwiddle** [comment]
Oh dear. These things do happen!

Actually GitHub has finally implemented collapsible files on some file/diff listings, so I could probably just remove this feature forever.

(The only disadvantage with Github's implementations are that the feature is on a little arrow `v` which is more effort to click that just clicking anywhere on the filename header. But I guess that's precisely the feature that is causing trouble for you!)

(Also I'm not sure if they have the feature on all listings with files. Maybe only on diffs at the moment.)

**Comment by joeytwiddle** [comment]
I have tried to disable it in f243806

**Comment by jerone** [comment]
Thanks, the update works great!
