### ISSUE TITLE
Youtube Thumb Likes Dislikes doesn't show

### ISSUE THREAD

**Issue by igoutta** [joeytwiddle/code#5]
The problem is that hovering over a video just shows a tooltip with the description of the video or a null register if doesn't find anyhting, but I don't saw any lightsaber with likes-dislikes proportions.

**Comment by joeytwiddle** [comment]
You are quite right. The thing's been broken for a while, and my attempts to fix it have gone slowly.

I tried using this alternative script for a while, but after a short while YouTube broke that one too! https://openuserjs.org/scripts/lednerg/Youtube_Video_Ratings_Bar_with_Power_Meter

**Comment by joeytwiddle** [comment]
Fixed in 71da368d
