### ISSUE TITLE
github dropdown notifications archive doesn't work

### ISSUE THREAD

**Issue by maricn** [joeytwiddle/code#9]
thanks for sharing your code! i found that clicking none of the buttons on a notification works - they just get grayed out as if they were clicked, but the notification entry stays there and no consequence (archive, unsub, bookmark) is observed..

https://github.com/joeytwiddle/code/blob/master/other/gm_scripts/github_notifications_dropdown/github_notifications_dropdown.user.js

1. seems like `listenForActionClicks` doesn't capture the form data properly (maybe due to new github notifications version)
2. maybe that function should be invoked with a small `setTimeout` at the end of the file

**Comment by joeytwiddle** [comment]
I think I resolved these around march 2023:

https://github.com/joeytwiddle/code/commits/master/other/gm_scripts/github_notifications_dropdown/github_notifications_dropdown.user.js

Although visual feedback is still lacking.
